### ISSUE TITLE
Django: Public Facing Tags View

### ISSUE THREAD

**Issue by sco1** [python-discord/site#178]
It would be handy to display a list of our current tags, and their descriptions, for folks to reference without having to invoke the command in-server.

Edit: tangentially related to #102

**Comment by lemonsaurus** [comment]
This issue is probably a good one for hacktoberfest. We have all the Tags stored in the database, and this just needs to display them. This will be a regular static page, so it's really just a matter of adding a page and writing some jinja to display it in a way that jives well with the rest of the site.

**Comment by CharlieADavies** [comment]
I'd like to try and do this over the next couple of days

**Comment by RohanJnr** [comment]
I will try this!

**Comment by lemonsaurus** [comment]
We've decided we will not be implementing this. Please see python-discord/bot#777 and #336 for more information on this.
