### ISSUE TITLE
Django: Oauth integration

### ISSUE THREAD

**Issue by scragly** [python-discord/site#201]
There's a need to integrate Discord OAuth for site account creation, linking and authorization, using the default Django Auth system so it's ubiquitous throughout all the site and any apps we use.

An existing solution was found with Django-Allauth that might suit the job and includes both Discord and Github as supported providers:
https://django-allauth.readthedocs.io/en/latest/index.html

The Github integration would be a great bonus as they could be utilised with the Code Jams.

**Comment by lemonsaurus** [comment]
I'm a fan of using allauth for this. It looks easy enough to implement, and would play well with both the overall page and the wiki.

What we'd want to do is make is so that, on first OAuth login with Discord, a django auth user is created. We'd then need to somehow figure out the Discord username, use this to check what the users roles are, and use the roles to determine which usergroup to put the user in. A user who was a moderator would get a moderator usergroup, and so on.

We don't need one usergroup for every single role on the server, just major ones. Right off the bat I'm thinking Developer, Contributor, Helper, Moderator, Admin, Owner. This will allow us to restrict editing and reading of certain pages to these roles, as well as eventually using the same usergroups to hide more interactive parts of the new website behind, such as editing tags, reviewing staff applications or ban appeals, that sort of thing.

Admins and Owners should both have full access to the site in every way.

**Comment by jchristgit** [comment]
Sounds good. I will do it.

**Comment by lemonsaurus** [comment]
Stale, unassigning @jchristgit

**Comment by gdude2002** [comment]
I'll work on this.

**Comment by gdude2002** [comment]
A few questions:

* Do we want to allow users to sign in with a username/email and password?
* Similarly, what about signing up? Social only?
* Do we want to fully replace the Django Admin login with this system?
* Where should the link to the accounts system be? (Login, my settings, etc)

**Comment by scragly** [comment]
I'd prefer to avoid standard logins and rely on both account creation and logins being reliant on oauth.

The django admin login should use this system, but is there a way to make sure that there's a way to still use the generic admin account as a backup still, just in case something goes wrong with oauth.

I don't know enough about the django login system to be able to comment on the last point.

**Comment by gdude2002** [comment]
> The django admin login should use this system, but is there a way to make sure that there's a way to still use the generic admin account as a backup still, just in case something goes wrong with oauth.
> 
> I don't know enough about the django login system to be able to comment on the 
last point.

When you talk about the Django auth system, you basically need to think about how access in general works. Django provides a login system with its own users, permissions and permissions groups - Allauth builds on top of this by allowing you to create or log into a Django user account using a social login. This goes for the admin account too - heck, you can login as the admin account and connect social accounts to it!

Allauth fully supports password-based logins. It does automatically sign you up if you login with a social account and don't already have a user account on the site, but it does not automatically sign you up if you enter a username and password on the login form.

Given this, perhaps it would be OK to have a separate "admin login" on the login page? Perhaps collapse it with JS?

**Comment by lemonsaurus** [comment]
okay, so to address some of these questions:
* Nobody should be able to sign in using usernames and passwords, except a sort of superadmin account which we can store in the keepass. This account should only be able to sign in via `/admin`, although you don't have to actually restrict this, we're just not gonna attach any social to it.
* Everybody else must sign in using a Discord account. Don't allow any other kind of social.
* The goal should be for us to match their Discord sign-in to our user table so that we can discover what rights to give them. This only works if it's a Discord sign-in, so it's imperative that we absolutely require this for new account creation.
* Beyond that, I don't think I see the need for any kind of a settings page or anything, but logging in should probably be on the navbar in the dropdown menu, at least for now.

**Comment by gdude2002** [comment]
> Nobody should be able to sign in using usernames and passwords, except a sort of superadmin account which we can store in the keepass. This account should only be able to sign in via /admin, although you don't have to actually restrict this, we're just not gonna attach any social to it.

That sounds fine - I need to investigate specifically how redirecting to login works, as right now it goes to the admin login regardless of whether allauth is there or not. My worry is that in making allauth the login redirect, we'll lose the admin login form - but then again, we can always re-add it ourselves if that's a problem.

> Everybody else must sign in using a Discord account. Don't allow any other kind of social.
> 
> The goal should be for us to match their Discord sign-in to our user table so that we can discover what rights to give them. This only works if it's a Discord sign-in, so it's imperative that we absolutely require this for new account creation.

As it stands, the signals setup I've written actually handles people connecting their Discord later (after GitHub) just fine - If we only want to allow people to sign up with Discord, then we can't allow them to sign in via GitHub at all (but we can still connect the account later). Unfortunately I'm not sure if it's realistic to be able to restrict this in the backend as the same URLs are likely to be used for login and connection, but I'll investigate this.

> Beyond that, I don't think I see the need for any kind of a settings page or anything, but logging in should probably be on the navbar in the dropdown menu, at least for now.

Sounds good to me! The settings pages I mentioned would be for connecting/disconnecting social accounts, updating your email address, etc. They're bundled with Allauth, but we can of course use only the pages we need.

**Comment by gdude2002** [comment]
I've been asked to make the messages look better than the current state of my PR. I'm going to do that by putting floating messages into one of the corners - however, the JS in `django-simple-bulma` uses the CSS `display` property to hide the messages when they're "closed". 

This works fine, but can't be animated. Would it be better to write our own JS for this in order to allow for that?

---

EDIT: That's just for closing transitions, by the way. Loading transitions work fine.


![Gif](https://cdn.discordapp.com/attachments/417755308891439124/630366645562638366/message-scroll-3.gif)

**Comment by gdude2002** [comment]
I can't decide between light-theme-inspired and dark-theme-inspired. What does everyone think?

![Example image](https://cdn.discordapp.com/attachments/417755308891439124/630373217730691072/unknown.png)

**Comment by Akarys42** [comment]
dark-theme-inspired for sure :)

**Comment by scragly** [comment]
Eventually I'd like to see a global dark theme we can choose for the site, so I'd prefer if the message box matches the current default light theme. 

However I also prefer the previous solid coloured message box over that one.

**Comment by gdude2002** [comment]
> However I also prefer the previous solid coloured message box over that one.

I designed them this way because lemon said he didn't really like the message boxes being so brightly coloured and in your face - I kind of agree, tbh.

I suggested this design since it matches up with Discord embeds.

> Eventually I'd like to see a global dark theme we can choose for the site, so I'd prefer if the message box matches the current default light theme.

Alright, that's no problem. Both types are in the CSS, the dark ones can be applied by adding `is-dark` if they're wanted before switchable themes are a thing.

**Comment by Akarys42** [comment]
Hmm the message box should be very easy to spot right? So what about making the box the invert of the current light theme?

**Comment by gdude2002** [comment]
I actually prefer the light ones myself, I think they fit better. They slide in, so they should be fairly obvious (especially when they overlap content).

By the way, I just realised that the current login system isn't quite kosher - need to actually bring people to a page to login so they can provide consent. That's alright, though.

**Comment by gdude2002** [comment]
Some progress has been made today.

First off, @lemonsaurus asked me to look into making the Bulma colours less vibrant. See below for what I've come up with (don't worry about text colour for now). Please let me know what you all think!

![Bulma Colours](https://cdn.discordapp.com/attachments/417755308891439124/630421793789968404/unknown.png)

Secondly, I've done a good bit of work on the login flow, and it's now functional to the specs we're looking for, as least as far as I can tell. There are no user pages, and currently no way to link a GitHub, but we can think about that a bit later.

[I uploaded an MP4 to Discord](https://cdn.discordapp.com/attachments/417755308891439124/630446269676126246/login-flow.mp4), which shows you how it works currently.

If anyone has any ideas on how to make the login function more obvious, I'd love to hear it. Please note, though, that the navbar itself is at maximum capacity - if we add any more elements to it, it'll overflow before we hit the next breakpoint.

**Comment by gdude2002** [comment]
Found a way to prevent Allauth from saving email addresses (via a very simple monkey patch). I've therefore simplified the login flow - [here's an MP4](https://cdn.discordapp.com/attachments/417755308891439124/630500812736561152/login-flow-2.mp4).
