### ISSUE TITLE
Breadcrumbs are visible right before headers

### ISSUE THREAD

**Issue by manusaurio** [python-discord/site#320]
_It seems breadcrumbs are not being hidden in any page from the More category/dropdown menu. It happens regardless of the device it's being shown on._

Update: the appearance of the site changes depending on whether I'm logged in or not. The layout makes some sense if I'm logged in.

Without logging in:
![image](https://user-images.githubusercontent.com/32289550/71601414-16da8400-2b32-11ea-8660-7abe3ad437c1.png)

Logged in:
![image](https://user-images.githubusercontent.com/32289550/71601433-24900980-2b32-11ea-93c4-bbaca51f1a5d.png)

**Comment by manusaurio** [comment]
I edited the issue. It turns out this doesn't depend on the device, user agent, viewport resolution or anything like that... this layout is used when a user hasn't logged in (it still looks like a bug, though, and not something intentional.)

**Comment by mdvsh** [comment]
Hey!
This issue still persists and I can work on it. 
Can I get assigned? 
Thanks

**Comment by jb3** [comment]
The reason why this happens is because our index page is actually private. Therefore the wiki system does not expose private pages and hides it.

If you visit a page like https://pythondiscord.com/pages/code-jams/code-jam-7/ then you will see the breadcrumbs are correctly filled in, even when the user is not authenticated.

I'm not sure whether we should consider this a bug, since we hope to have a site index at some point in the future which will resolve this issue when the index becomes public.

**Comment by Den4200** [comment]
Dewikification makes this no longer relevant.
