### ISSUE TITLE
Fix issues in https://web.dev/measure

### ISSUE THREAD

**Issue by Lvl4Sword** [python-discord/site#355]
According to https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fpythondiscord.com ( through https://web.dev/measure ), the Python Discord site currently scores 74/100 in Performance, 86/100 in Accessibility, 100/100 in Best Practices, and 91/100 in SEO.
These seem like some relatively easy things to implement for the speed ( and other ) bonuses they offer.

**Comment by lemonsaurus** [comment]
Here are actual actionable points:

## Don't load unused Bulma Extensions
Currently, we're not defining the `extensions` key in our `BULMA_SETTINGS` config dict. This means that **all Bulma extensions are being loaded**, which is stupid because we're not using any of them afaik.

To solve this, just add `extensions=[]` to `BULMA_SETTINGS`.

## Off-site asset loading has bad caching policies
We're loading a few assets from off-site - the Django logo from djangoproject.com, and some code jam banner from the githubusercontent CDN. These both have bad caching policies as a result. Fetch these images, add them to the site, and update the references to the local ones instead.

## Resource-blocking assets
We don't preload CSS, and we don't defer loading of JS. This should be fixed.

This fix mostly needs to happen in `django-simple-bulma`, so see https://github.com/python-discord/django-simple-bulma/issues/45 - but we may be importing other stuff (local css, maybe fontawesome?) that could use this treatment as well.

## Minification of JS and CSS
We don't minify JS and CSS.

Same story here - this mostly should be addressed in `django-simple-bulma` (https://github.com/python-discord/django-simple-bulma/issues/44) but may need to be addressed for a few local files as well.

## Images should be the right size
There's probably some images resized by width and height parameters or css - this is wasteful compared to just serving them at the right size. So, just resize those assets and remove the resizing.

**Comment by MarkKoz** [comment]
@Lvl4Sword Are you still working on this?

**Comment by Lvl4Sword** [comment]
@MarkKoz I've been meaning to, just been busy with other things.

**Comment by Lvl4Sword** [comment]
@MarkKoz Not anymore, no.
Since I'm not part of the organization, I'll need to be removed from this. Thanks :+1:
