### ISSUE TITLE
Dewikification: Site Index

### ISSUE THREAD

**Issue by mbaruh** [python-discord/site#399]
**Remember to target the `dewikification` branch with this pull request**

I think it's high time we had an issue on this.

Currently, our index page looks like this:
![image](https://user-images.githubusercontent.com/18114431/94465974-63d6ae00-01c9-11eb-86ea-874a8dcbec64.png)

Which isn't very good, and makes the site pretty difficult to navigate, considering this page is referred to by all breadcrumbs.

The challenge is to make a page which is dynamic according to:
* The pages which exist.
* The pages the user has access to.

And of course to make the page look nice so it's easy to find what you're looking for.

**Comment by Den4200** [comment]
The dewikification project should take care of this. We're moving away from
our current wiki in the near future, so this becomes pretty irrelevant.

**Comment by mbaruh** [comment]
I agree if we were to do this now it would become pretty irrelevant.
We should do this near the end of the project

**Comment by lemonsaurus** [comment]
> The pages the user has access to.

This is no longer a concern, since we're stripping out auth.

Beyond that, I'm not sure I understand what this would be, but it sounds a bit like a sitemap. Sitemaps are ugly. Let's not make one. There's no reason we need a single page that contains all the content on our website. Instead, we'll have several pages where that information is logically indexed. The events page will contain all the event stuff, the contributing page has the contribution pages, the privacy page has our data reviews, and the resources page has pretty much everything else.

If you're looking for something specific, you can use the search function, which there is already an issue for here: https://github.com/python-discord/site/issues/366
