### ISSUE TITLE
How about translating the site into Korean?

### ISSUE THREAD

**Issue by KeuHeum** [python-discord/site#562]
How about translating the site into Korean?
There is no discord.py guide in Korean, so many beginners are having a hard time. How about translating the discord.py guide to Korean for beginners?

**Comment by HassanAbouelela** [comment]
Hey, thanks for the suggestion! I will have to shoot this proposal (as well as other translations) down for a few reasons:

- A translation is a lot of work, from finding people to do the initial translation, to finding reviewers so people don’t slip in their own “thoughts” in there.
- Maintenance is going to be very hard, because each change would require the same requirements as the initial conversion.

Translation and providing people with good content is a good cause, but it isn’t feasible for us. It’s feasible if you have a large pool of trusted volunteers, or employees you can pay, neither of which we have.

**Comment by RohanJnr** [comment]
@HassanAbouelela has valid points regarding this issue and which cannot be implemented as of now or in the near future. I will be closing this issue.
